### ISSUE TITLE
stderr: gazebo_ros  

### ISSUE THREAD

**Issue by dvogureckiy99** [ros-simulation/gazebo_ros_pkgs#1471]
I use ubuntu 20.04
ros 2 humble

I git clone --branch ros2 https://github.com/ros-simulation/gazebo_ros_pkgs.git to ros2_humble/src
with trying `colcon build --symlink-install --packages-select gazebo_dev gazebo_msgs gazebo_ros gazebo_plugins gazebo_ros_pkgs`
 I have got error: 
```Starting >>> gazebo_ros    
--- stderr: gazebo_ros                                
CMake Error at /home/dvogureckiy99/ros2_humble/install/gazebo_dev/share/gazebo_dev/cmake/gazebo_dev-extras.cmake:3 (find_package):
  By not providing "Findgazebo.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gazebo", but
  CMake did not find one.

  Could not find a package configuration file provided by "gazebo" with any
  of the following names:

    gazeboConfig.cmake
    gazebo-config.cmake

  Add the installation prefix of "gazebo" to CMAKE_PREFIX_PATH or set
  "gazebo_DIR" to a directory containing one of the above files.  If "gazebo"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /home/dvogureckiy99/ros2_humble/install/gazebo_dev/share/gazebo_dev/cmake/gazebo_devConfig.cmake:41 (include)
  CMakeLists.txt:26 (find_package)


---
Failed   <<< gazebo_ros [11.0s, exited with code 1]
```

And another one error appeared after command `ros2 run gazebo_ros spawn_entity.py -entity solo12dof_quadruped -file ~/git/robot_programming_course/catkin_ws/src/solo12dof_quadruped/urdf/solo12dof_quadruped.urdf -x 0 -y 0 -z 1`:
```
[INFO] [1680612612.664726268] [spawn_entity]: Spawn Entity started
[INFO] [1680612612.665737877] [spawn_entity]: Loading entity XML from file /home/dvogureckiy99/git/robot_programming_course/catkin_ws/src/solo12dof_quadruped/urdf/solo12dof_quadruped.urdf
Traceback (most recent call last):
  File "/home/dvogureckiy99/gazebo_ros_pkgs_ws/install/gazebo_ros/lib/gazebo_ros/spawn_entity.py", line 370, in <module>
    main()
  File "/home/dvogureckiy99/gazebo_ros_pkgs_ws/install/gazebo_ros/lib/gazebo_ros/spawn_entity.py", line 365, in main
    exit_code = spawn_entity_node.run()
  File "/home/dvogureckiy99/gazebo_ros_pkgs_ws/install/gazebo_ros/lib/gazebo_ros/spawn_entity.py", line 192, in run
    xml_parsed = ElementTree.fromstring(entity_xml)
  File "src/lxml/etree.pyx", line 3235, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1871, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
[ros2run]: Process exited with failure 1
```

**Comment by EduardoWS** [comment]
managed to solve? I have the same error
