### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by tfoote** [ros-simulation/gazebo_ros_pkgs#24]
This breaks the buildfarm: http://jenkins.willowgarage.com:8080/job/_hydro-reconfigure-release-jobs/136/console

```
Traceback (most recent call last):
  File "./scripts/create_release_jobs.py", line 211, in <module>
    release_jobs.check_for_circular_dependencies(dependencies)
  File "/var/lib/jenkins/jobs/_hydro-reconfigure-release-jobs/workspace/buildfarm/release_jobs.py", line 125, in check_for_circular_dependencies
    _remove_leafs_recursively(rev_deps)
  File "/var/lib/jenkins/jobs/_hydro-reconfigure-release-jobs/workspace/buildfarm/release_jobs.py", line 140, in _remove_leafs_recursively
    raise RuntimeError('The following packages contain a dependency cycle: %s' % ', '.join(sorted(deps.keys())))
RuntimeError: The following packages contain a dependency cycle: ros-hydro-gazebo-plugins, ros-hydro-gazebo-ros
```

**Comment by davetcoleman** [comment]
Fixed yesterday here: https://github.com/osrf/gazebo_ros_pkgs/commit/f1f0850f65683351dd807edc4007cee93198173b

I think I correctly pushed an updated 2.0.1 version to bloom

**Comment by tfoote** [comment]
You need to update the rosdistro to index the new release then.

**Comment by davetcoleman** [comment]
Like this https://github.com/ros/rosdistro/pull/1039 ?

**Comment by tfoote** [comment]
exactly

**Comment by davetcoleman** [comment]
thanks!
