### ISSUE TITLE
Delete Model Not Working

### ISSUE THREAD

**Issue by hboortz** [ros-simulation/gazebo_ros_pkgs#38]
The "Delete Model" command is not working from this tutorial: http://gazebosim.org/wiki/Tutorials/1.9/ROS_Communication_with_Gazebo . 

When you run 

```
rosservice call gazebo/delete_model '{model_name: rrbot1}'
```

And rrbot1 does exist, a segfault occurs:

```
DEBUG ros.gazebo_ros: Waiting for model deletion (rrbot)
Segmentation fault (core dumped)
/home/dave/ros/ws_gazebo/src/gazebo_ros_pkgs/gazebo_ros/scripts/gazebo: 25: kill: invalid signal number or name: SIGINT
```

**Comment by davetcoleman** [comment]
I have confirmed this issue.

**Comment by hsu** [comment]
For me gzserver continues to run, but gzclient crashes with following backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fc0a6fc2700 (LWP 23196)]
0x00007fc0be918969 in glGenBuffersARB () from /usr/lib/x86_64-linux-gnu/libGL.so.1
(gdb) bt
#0  0x00007fc0be918969 in glGenBuffersARB () from /usr/lib/x86_64-linux-gnu/libGL.so.1
#1  0x00007fc07ef3f19e in Ogre::GLHardwareVertexBuffer::GLHardwareVertexBuffer(Ogre::HardwareBufferManagerBase*, unsigned long, unsigned long, Ogre::HardwareBuffer::Usage, bool)
    () from /usr/lib/x86_64-linux-gnu/OGRE-1.7.4/RenderSystem_GL.so
#2  0x00007fc07ef392b6 in Ogre::GLHardwareBufferManagerBase::createVertexBuffer(unsigned long, unsigned long, Ogre::HardwareBuffer::Usage, bool) ()
   from /usr/lib/x86_64-linux-gnu/OGRE-1.7.4/RenderSystem_GL.so
#3  0x00007fc07ef498b5 in ?? () from /usr/lib/x86_64-linux-gnu/OGRE-1.7.4/RenderSystem_GL.so
#4  0x00007fc0c4d01a99 in gazebo::rendering::DynamicRenderable::PrepareHardwareBuffers (this=0x7fc03f1819d0, vertexCount=24, indexCount=0)
    at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/rendering/DynamicRenderable.cc:166
#5  0x00007fc0c4d0046c in gazebo::rendering::DynamicLines::FillHardwareBuffers (this=0x7fc03f1819d0)
    at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/rendering/DynamicLines.cc:135
#6  0x00007fc0c4d896f6 in gazebo::rendering::WireBox::Init (this=0x7fc098018320, _box=...)
    at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/rendering/WireBox.cc:98
#7  0x00007fc0c4d89809 in gazebo::rendering::WireBox::WireBox (this=0x7fc098018320, _parent=..., _box=...)
    at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/rendering/WireBox.cc:33
#8  0x00007fc0c4d7805d in gazebo::rendering::Visual::SetHighlighted (this=0x666d6e0, _highlighted=<optimized out>)
    at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/rendering/Visual.cc:1188
#9  0x00000000004a94d8 in SetSelectedVisual (this=0x15ce220, _vis=...) at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/gui/GLWidget.cc:1030
#10 gazebo::gui::GLWidget::SetSelectedVisual (this=0x15ce220, _vis=...) at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/gui/GLWidget.cc:1019
#11 0x00000000004a9630 in gazebo::gui::GLWidget::OnSelectionMsg (this=0x15ce220, _msg=...)
    at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/gui/GLWidget.cc:1008
#12 0x00000000004b10eb in operator() (a0=..., this=0x15f5f70) at /usr/include/boost/function/function_template.hpp:1013
#13 gazebo::transport::CallbackHelperT<gazebo::msgs::Selection>::HandleData(std::string const&, boost::function<void (unsigned int)>, unsigned int) (this=0x15f5f60, 
    _newdata=..., _cb=..., _id=0) at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/transport/CallbackHelper.hh:138
#14 0x00007fc0c504dba0 in gazebo::transport::Node::ProcessIncoming (this=0x15f4670) at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/transport/Node.cc:203
#15 0x00007fc0c5058e5f in gazebo::transport::TopicManager::ProcessNodes (this=0x8d4ba0, _onlyOut=false)
    at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/transport/TopicManager.cc:191
#16 0x00007fc0c5042003 in gazebo::transport::ConnectionManager::RunUpdate (this=0x8d4d40)
    at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/transport/ConnectionManager.cc:279
#17 0x00007fc0c5043202 in gazebo::transport::ConnectionManager::Run (this=0x8d4d40)
    at /home/hsu/projects/catkin_ws/hydro/src_isolated/gazebo_1.9/gazebo/transport/ConnectionManager.cc:310
#18 0x00007fc0c0d92ce9 in thread_proxy () from /usr/lib/libboost_thread.so.1.46.1
#19 0x00007fc0c2bfee9a in start_thread (arg=0x7fc0a6fc2700) at pthread_create.c:308
#20 0x00007fc0c10933fd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#21 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by j-rivero** [comment]
I haven't been able to reproduce this problem with ROS Jade. Please reopen if it still present on your system.
